#!/usr/bin/env python3
"""Shared utilities for the FIQA standalone-script pipeline.

The module deliberately contains no project-specific absolute paths. Every stage
reads the JSON configuration produced by ``setup_project.py`` and may override
its input path from the command line.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Iterable, Sequence

import numpy as np
import pandas as pd

TARGET = "cr_fiqa_score"
IMAGE_COLUMN = "index"
IDENTITY_COLUMN = "cls"
GROUP_COLUMN = "group"

CONTINUOUS_FEATURES = [
    "age",
    "smile",
    "moustache",
    "beard",
    "sideburns",
    "head_roll",
    "head_yaw",
    "head_pitch",
    "blur",
    "exposure",
    "noise",
]

PRIMARY_CONTINUOUS_FEATURES = [
    "smile",
    "moustache",
    "beard",
    "sideburns",
    "head_roll",
    "head_yaw",
    "head_pitch",
    "blur",
    "exposure",
    "noise",
]

DEMOGRAPHIC_CONTINUOUS_FEATURES = [
    "smile",
    "head_roll",
    "head_yaw",
    "head_pitch",
    "blur",
    "exposure",
    "noise",
]

FACIAL_HAIR_FEATURES = ["moustache", "beard", "sideburns"]

BINARY_FEATURES = [
    "mask",
    "headWear",
    "glasses",
    "eye_makeup",
    "lip_makeup",
    "forehead_occluded",
    "eye_occluded",
    "mouth_occluded",
]

CATEGORICAL_FEATURES = [GROUP_COLUMN]

EXPECTED_GROUP_ORDER = [
    "Asian Woman",
    "Asian Man",
    "Black Woman",
    "Black Man",
    "Caucasian Woman",
    "Caucasian Man",
]

BINARY_MAPPING = {
    True: 1.0,
    False: 0.0,
    "true": 1.0,
    "false": 0.0,
    "True": 1.0,
    "False": 0.0,
    "yes": 1.0,
    "no": 0.0,
    "Yes": 1.0,
    "No": 0.0,
    "1": 1.0,
    "0": 0.0,
    1: 1.0,
    0: 0.0,
    1.0: 1.0,
    0.0: 0.0,
}


def normalize_path(path: str | Path) -> Path:
    """Return an absolute path after expanding the user home directory."""
    return Path(path).expanduser().resolve()


def load_runtime_config(path: str | Path) -> dict[str, Any]:
    """Load and validate the JSON file generated by ``setup_project.py``."""
    config_path = normalize_path(path)
    if not config_path.exists():
        raise FileNotFoundError(
            f"Runtime configuration not found: {config_path}. "
            "Run scripts/setup_project.py first or pass another --config."
        )
    if not config_path.is_file():
        raise ValueError(f"Configuration path is not a file: {config_path}")

    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON configuration: {config_path}") from exc

    if not isinstance(config, dict):
        raise ValueError("Runtime configuration must contain a JSON object.")

    required = {"project_dir", "results_dir", "models_dir"}
    missing = sorted(required.difference(config))
    if missing:
        raise KeyError(f"Runtime configuration is missing keys: {missing}")

    return config


def config_path(
    config: dict[str, Any],
    key: str,
    override: str | Path | None = None,
    *,
    required: bool = True,
) -> Path | None:
    """Resolve a path from a CLI override or runtime-config key."""
    raw: str | Path | None = override if override is not None else config.get(key)
    if raw in (None, ""):
        if required:
            raise KeyError(
                f"Path '{key}' is missing from the runtime configuration and "
                "was not supplied as a command-line override."
            )
        return None
    return normalize_path(raw)


def ensure_directory(path: str | Path) -> Path:
    directory = normalize_path(path)
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def require_file(path: str | Path, label: str) -> Path:
    candidate = normalize_path(path)
    if not candidate.exists():
        raise FileNotFoundError(f"{label} not found: {candidate}")
    if not candidate.is_file():
        raise ValueError(f"{label} is not a file: {candidate}")
    return candidate


def find_merged_data(
    config: dict[str, Any],
    override: str | Path | None = None,
) -> Path:
    """Locate the merged annotation/FIQA table without hardcoded user paths.

    Resolution order:
    1. explicit ``--data`` override;
    2. optional ``merged_data_file`` key in the runtime config;
    3. output created by ``extract_scores.py``;
    4. legacy project-root filename for backward compatibility.
    """
    if override is not None:
        return require_file(override, "Merged dataset")

    configured = config.get("merged_data_file")
    candidates: list[Path] = []
    if configured:
        candidates.append(normalize_path(configured))

    results_dir = config_path(config, "results_dir")
    project_dir = config_path(config, "project_dir")
    assert results_dir is not None and project_dir is not None

    candidates.extend(
        [
            results_dir / "01_score_extraction" / "diveface_fiqa_merged.csv",
            project_dir / "diveface_fiqa_merged.csv",
        ]
    )

    for candidate in candidates:
        if candidate.exists() and candidate.is_file():
            return candidate.resolve()

    checked = "\n".join(f"- {path}" for path in candidates)
    raise FileNotFoundError(
        "Merged dataset could not be found. Run extract_scores.py or pass "
        f"--data explicitly. Checked:\n{checked}"
    )


def stage_paths(
    config: dict[str, Any],
    stage_name: str,
    *,
    include_models: bool = False,
) -> dict[str, Path]:
    """Create and return standard result folders for one pipeline stage."""
    results_root = config_path(config, "results_dir")
    models_root = config_path(config, "models_dir")
    assert results_root is not None and models_root is not None

    root = ensure_directory(results_root / stage_name)
    paths = {
        "root": root,
        "tables": ensure_directory(root / "tables"),
        "figures": ensure_directory(root / "figures"),
    }
    if include_models:
        paths["models"] = ensure_directory(models_root / stage_name)
    return paths


def save_json(data: Any, path: str | Path) -> Path:
    output = normalize_path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(data, indent=2, ensure_ascii=False, default=_json_default),
        encoding="utf-8",
    )
    return output


def _json_default(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return None if not np.isfinite(value) else float(value)
    if isinstance(value, (np.bool_,)):
        return bool(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")


def validate_columns(
    frame: pd.DataFrame,
    columns: Sequence[str],
    *,
    context: str,
) -> None:
    missing = [column for column in columns if column not in frame.columns]
    if missing:
        raise KeyError(f"{context} is missing required columns: {missing}")


def available_features(frame: pd.DataFrame, features: Sequence[str]) -> list[str]:
    """Return requested features that exist and are not entirely missing."""
    return [
        feature
        for feature in features
        if feature in frame.columns and frame[feature].notna().any()
    ]


def convert_binary_series(series: pd.Series, feature: str) -> pd.Series:
    """Convert common boolean/0-1 representations to float 0/1 values."""
    converted = series.map(BINARY_MAPPING)

    # Numeric values such as numpy integers may not be hit by ``map`` in all
    # pandas versions, so accept exact numeric 0/1 values explicitly.
    numeric = pd.to_numeric(series, errors="coerce")
    converted = converted.where(converted.notna(), numeric.where(numeric.isin([0, 1])))

    invalid = series.notna() & converted.isna()
    if invalid.any():
        examples = series.loc[invalid].astype(str).drop_duplicates().head(5).tolist()
        raise ValueError(
            f"Feature '{feature}' contains unsupported binary values: {examples}"
        )

    return converted.astype(float)


def prepare_numeric_columns(
    frame: pd.DataFrame,
    numeric_features: Sequence[str],
    binary_features: Sequence[str],
    *,
    target: str = TARGET,
) -> pd.DataFrame:
    """Return a copy with consistently numeric feature and target columns."""
    prepared = frame.copy()

    for column in list(dict.fromkeys([*numeric_features, target])):
        if column in prepared.columns:
            prepared[column] = pd.to_numeric(prepared[column], errors="coerce")

    for feature in binary_features:
        if feature in prepared.columns:
            prepared[feature] = convert_binary_series(prepared[feature], feature)

    return prepared


def group_order(values: Iterable[Any]) -> list[str]:
    present = [str(value) for value in pd.Series(list(values)).dropna().unique()]
    ordered = [group for group in EXPECTED_GROUP_ORDER if group in present]
    ordered.extend(sorted(set(present).difference(ordered)))
    return ordered


def safe_fdr(p_values: Sequence[float], alpha: float = 0.05) -> tuple[np.ndarray, np.ndarray]:
    """Benjamini-Hochberg correction that preserves NaN positions."""
    from statsmodels.stats.multitest import multipletests

    values = np.asarray(p_values, dtype=float)
    adjusted = np.full(values.shape, np.nan, dtype=float)
    rejected = np.full(values.shape, False, dtype=bool)
    valid = np.isfinite(values)

    if valid.any():
        reject_valid, adjusted_valid, _, _ = multipletests(
            values[valid], alpha=alpha, method="fdr_bh"
        )
        adjusted[valid] = adjusted_valid
        rejected[valid] = reject_valid

    return adjusted, rejected


def regression_metrics(y_true: Sequence[float], y_pred: Sequence[float]) -> dict[str, float]:
    from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

    y_true_array = np.asarray(y_true, dtype=float)
    y_pred_array = np.asarray(y_pred, dtype=float)
    return {
        "rmse": float(math.sqrt(mean_squared_error(y_true_array, y_pred_array))),
        "mae": float(mean_absolute_error(y_true_array, y_pred_array)),
        "r2": float(r2_score(y_true_array, y_pred_array)),
    }


def make_preprocessor(
    continuous_features: Sequence[str],
    binary_features: Sequence[str],
    categorical_features: Sequence[str],
):
    """Create the preprocessing pipeline shared by training and optimization."""
    from sklearn.compose import ColumnTransformer
    from sklearn.impute import SimpleImputer
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import OneHotEncoder, StandardScaler

    transformers = []

    if continuous_features:
        transformers.append(
            (
                "continuous",
                Pipeline(
                    [
                        ("imputer", SimpleImputer(strategy="median")),
                        ("scaler", StandardScaler()),
                    ]
                ),
                list(continuous_features),
            )
        )

    if binary_features:
        transformers.append(
            (
                "binary",
                Pipeline(
                    [
                        ("imputer", SimpleImputer(strategy="most_frequent")),
                    ]
                ),
                list(binary_features),
            )
        )

    if categorical_features:
        transformers.append(
            (
                "categorical",
                Pipeline(
                    [
                        ("imputer", SimpleImputer(strategy="most_frequent")),
                        (
                            "onehot",
                            OneHotEncoder(handle_unknown="ignore", sparse_output=False),
                        ),
                    ]
                ),
                list(categorical_features),
            )
        )

    if not transformers:
        raise ValueError("At least one predictor is required to build a preprocessor.")

    return ColumnTransformer(transformers=transformers, remainder="drop")


def transformed_feature_names(pipeline_or_preprocessor: Any) -> list[str]:
    """Return transformed feature names from a fitted pipeline/preprocessor."""
    preprocessor = pipeline_or_preprocessor
    if hasattr(pipeline_or_preprocessor, "named_steps"):
        preprocessor = pipeline_or_preprocessor.named_steps.get("preprocessor")

    if preprocessor is None:
        raise ValueError("No preprocessor was found in the fitted object.")

    try:
        return [str(name) for name in preprocessor.get_feature_names_out()]
    except Exception:
        transformed = preprocessor.transform(pd.DataFrame([{}]))
        return [f"feature_{index}" for index in range(transformed.shape[1])]


def original_feature_from_transformed(
    transformed_name: str,
    original_features: Sequence[str],
) -> str:
    """Map a ColumnTransformer output name back to the original predictor."""
    cleaned = transformed_name.split("__", 1)[-1]

    if cleaned in original_features:
        return cleaned

    # Match longest names first to avoid prefix collisions.
    for feature in sorted(original_features, key=len, reverse=True):
        if cleaned == feature or cleaned.startswith(f"{feature}_"):
            return feature

    return cleaned


def load_split_assignments(path: str | Path) -> pd.DataFrame:
    split_path = require_file(path, "Identity-aware split file")
    split = pd.read_csv(split_path)
    validate_columns(
        split,
        [IMAGE_COLUMN, IDENTITY_COLUMN, "source_dataframe_index", "split"],
        context="Split table",
    )
    if not set(split["split"].dropna().unique()).issubset({"train", "test"}):
        raise ValueError("Split table contains values other than 'train' and 'test'.")
    return split


def reconstruct_split(
    frame: pd.DataFrame,
    split: pd.DataFrame,
    feature_columns: Sequence[str],
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Reproduce the exact row-level split saved by ``train_models.py``."""
    validate_columns(
        frame,
        [IMAGE_COLUMN, IDENTITY_COLUMN, TARGET, *feature_columns],
        context="Merged dataset",
    )

    working = frame.copy()
    working["source_dataframe_index"] = working.index.astype(int)

    merge_keys = ["source_dataframe_index", IMAGE_COLUMN, IDENTITY_COLUMN]
    assignments = split[merge_keys + ["split"]].copy()
    reconstructed = working.merge(
        assignments,
        on=merge_keys,
        how="inner",
        validate="one_to_one",
    )

    if len(reconstructed) != len(split):
        raise ValueError(
            "The saved split cannot be reconstructed exactly from the current "
            "merged dataset. Ensure the same data file is being used."
        )

    train = reconstructed.loc[reconstructed["split"] == "train"].copy()
    test = reconstructed.loc[reconstructed["split"] == "test"].copy()

    if train.empty or test.empty:
        raise ValueError("Reconstructed train or test split is empty.")

    return train, test


def print_saved_files(root: str | Path) -> None:
    root_path = normalize_path(root)
    for path in sorted(root_path.rglob("*")):
        if path.is_file():
            print(f"- {path.relative_to(root_path)}")
